// We do not import the mdx files here inorder to make use of dynamic imports inside $postId file
export interface Recipe {
	slug: string
	title: string
	publishDate: string
	description: string
	to: string
	readingTime: string
	image: string
}

export type RecipeList = Array<Recipe>

export const recipeList: RecipeList = [
	{
		slug: 'hello-world',
		title: 'Portobello Mushroom Soup',
		publishDate: '30 Nov 2021',
		description: 'Every blog starts with a single post. This is yours. Make it great.',
		to: '/recipes/hello-world',
		readingTime: '1 min',
		image: '../assets/images/example.jpeg',
	},
	{
		slug: 'markdown-test',
		title: 'Vegan Schnitzels',
		publishDate: '01 Dec 2021',
		description:
			'A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Use it as a starting point for applying your own styles.',
		to: '/recipes/markdown-test',
		readingTime: '5 min',
		image: '../assets/images/1.jpeg',
	},
	{
		slug: 'another-markdown',
		title: 'Blueberry cheesecake',
		publishDate: '15 Dec 2021',
		description:
			' A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.',
		to: '/recipes/another-markdown',
		readingTime: '10 min',
		image: '../assets/images/2.webp',
	},
	{
		slug: 'hello-world',
		title: 'Portobello Mushroom Soup',
		publishDate: '30 Nov 2021',
		description: 'Every blog starts with a single post. This is yours. Make it great.',
		to: '/recipes/hello-world',
		readingTime: '1 min',
		image: '../assets/images/3.jpeg',
	},
	{
		slug: 'markdown-test',
		title: 'Vegan Schnitzels',
		publishDate: '01 Dec 2021',
		description:
			'A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Use it as a starting point for applying your own styles.',
		to: '/recipes/markdown-test',
		readingTime: '5 min',
		image: '../assets/images/4.jpg',
	},
	{
		slug: 'another-markdown',
		title: 'Blueberry cheesecake',
		publishDate: '15 Dec 2021',
		description:
			' A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.',
		to: '/recipes/another-markdown',
		readingTime: '10 min',
		image: '../assets/images/5.jpeg',
	},
	{
		slug: 'hello-world',
		title: 'Portobello Mushroom Soup',
		publishDate: '30 Nov 2021',
		description: 'Every blog starts with a single post. This is yours. Make it great.',
		to: '/recipes/hello-world',
		readingTime: '1 min',
		image: '../assets/images/6.jpeg',
	},
	{
		slug: 'markdown-test',
		title: 'Vegan Schnitzels',
		publishDate: '01 Dec 2021',
		description:
			'A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Use it as a starting point for applying your own styles.',
		to: '/recipes/markdown-test',
		readingTime: '5 min',
		image: '../assets/images/7.jpeg',
	},
	{
		slug: 'another-markdown',
		title: 'Blueberry cheesecake',
		publishDate: '15 Dec 2021',
		description:
			' A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.',
		to: '/recipes/another-markdown',
		readingTime: '10 min',
		image: '../assets/images/8.jpeg',
	},
	{
		slug: 'hello-world',
		title: 'Portobello Mushroom Soup',
		publishDate: '30 Nov 2021',
		description: 'Every blog starts with a single post. This is yours. Make it great.',
		to: '/recipes/hello-world',
		readingTime: '1 min',
		image: '../assets/images/9.jpeg',
	},
	{
		slug: 'markdown-test',
		title: 'Vegan Schnitzels',
		publishDate: '01 Dec 2021',
		description:
			'A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Use it as a starting point for applying your own styles.',
		to: '/recipes/markdown-test',
		readingTime: '5 min',
		image: '../assets/images/1.jpeg',
	},
	{
		slug: 'another-markdown',
		title: 'Blueberry cheesecake',
		publishDate: '15 Dec 2021',
		description:
			' A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.',
		to: '/recipes/another-markdown',
		readingTime: '10 min',
		image: '../assets/images/3.jpeg',
	},
]
